### ISSUE TITLE
Helium Ledger App Transaction

### ISSUE THREAD

**Issue by jack12z** [helium/helium-ledger-app#29]
When performing a transaction using the ledger nano s, the user is unable to successfully send tokens to another wallet. I am currently running windows 10 using command prompt to perform the transaction. Here is the full request:

C:\Users\jackz\Downloads\Helium Ledger>helium-ledger-app balance
Communicating with Ledger - follow prompts on screen
+-----------------------------------------------------+-------------+--------------+-----------------+
| Address                                             | Balance HNT | Data Credits | Security Tokens |
+-----------------------------------------------------+-------------+--------------+-----------------+
| 12xLQvoRQJwXvNp4UKp1CRfU2nHAizCnVeyxSEGx1ACPJFyhegk | 1.00000000  | 0            | 0               |
+-----------------------------------------------------+-------------+--------------+-----------------+

C:\Users\jackz\Downloads\Helium Ledger>helium-ledger-app pay 14knLibJkNZ5P348AvDaMbYgb2RzNxJcQLYVB9UcWB143DknWRQ hnt 1.0
Communicating with Ledger - follow prompts on screen
Creating transaction for:
      1.00000000 HNT
        =
      100000000 Bones
Transaction fee: 35000 DC (1 DC = $.00001)
If account has no DCs, HNT will be burned automatically to fund transaction based on current oracle price
+-----------------------------------------------------+------------+-------+---------------------------------------------+
| Payee                                               | Amount HNT | Nonce | Hash                                        |
+-----------------------------------------------------+------------+-------+---------------------------------------------+
| 14knLibJkNZ5P348AvDaMbYgb2RzNxJcQLYVB9UcWB143DknWRQ | 1.00000000 | 1     | sTTJfFCkUQLbhfe5-aTVaFtbWZsho7vFmSEk2MeINJc |
+-----------------------------------------------------+------------+-------+---------------------------------------------+

C:\Users\jackz\Downloads\Helium Ledger>

I have tried performing the transactions before, but even then it was not successful. Even after authorizing on the ledger device itself it still seems to fail.

![image](https://user-images.githubusercontent.com/63269945/116029056-782b3e00-a626-11eb-80d8-b1fa42454d58.png)

**Comment by jack12z** [comment]
RESOLVED: Need to leave a balance of hnt equivalent of 35,000 D.C. to perform transaction. I thought that the automatically burned HNT would be from the amount sent, not the wallet balance

**Comment by jack12z** [comment]
UPDATE: After adjusting the amount to send to 0.9, the transaction still has not gone through.

C:\Users\jackz\Downloads\Helium Ledger>helium-ledger-app pay 14knLibJkNZ5P348AvDaMbYgb2RzNxJcQLYVB9UcWB143DknWRQ hnt 0.99
Communicating with Ledger - follow prompts on screen
Creating transaction for:
      0.99000000 HNT
        =
      99000000 Bones
Transaction fee: 35000 DC (1 DC = $.00001)
If account has no DCs, HNT will be burned automatically to fund transaction based on current oracle price
+-----------------------------------------------------+------------+-------+---------------------------------------------+
| Payee                                               | Amount HNT | Nonce | Hash                                        |
+-----------------------------------------------------+------------+-------+---------------------------------------------+
| 14knLibJkNZ5P348AvDaMbYgb2RzNxJcQLYVB9UcWB143DknWRQ | 0.99000000 | 1     | 5XyytOTcddbm-2z4FVqgD_HsmHmvFaMnRMyhhOZQ4ck |
+-----------------------------------------------------+------------+-------+---------------------------------------------+

**Comment by lthiery** [comment]
@jack12z you're still not leaving behind enough HNT. I have a companion app update that will point you to the API for monitoring:
https://api.helium.io/v1/pending_transactions/5XyytOTcddbm-2z4FVqgD_HsmHmvFaMnRMyhhOZQ4ck

You are leaving behind 0.01 HNT. Even with an optimistic oracle price of $15, that's only 15000 DCs. Trying transferring something like 0.97 HNT.
